server:
  port: 8081
spring:
  security:
    oauth2:
      client:
        registration: ## ????? ??
          keycloak:
            clientId: oauth2-client-app # ??? ???? ??? ????? ???
            clientSecret: BgajNoXrRdKav0Q5jlFDiUNafyGHbfAa # ??? ???? ??? ????? ????
            clientName: oauth2-client-app # ????? ??
            redirectUri: http://localhost:8081/login/oauth2/code/keycloak # ????? URI
            authorizationGrantType: authorization_code # OAuth 2.0 ?? ?? ??
            clientAuthenticationMethod: client_secret_basic # ????? ?? ?? post, none ...
            scope: openid,profile,email #  ???? ?? ?? ??
        provider: ## ??? ??? ??
          keycloak:
            authorizationUri: http://localhost:8080/realms/oauth2/protocol/openid-connect/auth # ?? ?????
            tokenUri: http://localhost:8080/realms/oauth2/protocol/openid-connect/token # ?? ?????
            issuerUri: http://localhost:8080/realms/oauth2 # ??? ???? ???
            userInfoUri: http://localhost:8080/realms/oauth2/protocol/openid-connect/userinfo # ??? ?? ?????
            jwkSetUri: http://localhost:8080/realms/oauth2/protocol/openid-connect/certs # JSON Web Key Set ?????
            userNameAttribute: preferred_username # ??? ?? ??